export const ActionTypes  = {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
    FILTER_PRODUCTS: "FILTER_PRODUCTS",
    GET_PRODUCT: "GET_PRODUCT"
}