export const ActionTypes  = {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
    GET_PRODUCT: "GET_PRODUCT",
    ADD_FILTERS: "ADD_FILTERS",
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART"
}